### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by siberianguy** [ygoe/ViewModelKit#1]
Installed ViewModelKit but my application is not compiled. Here is an error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Sequence contains no matching element
StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ViewModelKit.Fody.References..ctor(ModuleDefinition moduleDef) in C:\Source\DevTools\ViewModelKit\ViewModelKit.Fody\References.cs:line 54
   at ViewModelKit.Fody.ModuleWeaver.Execute() in C:\Source\DevTools\ViewModelKit\ViewModelKit.Fody\ModuleWeaver.cs:line 57
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
System.Core
TargetSite:
TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])	Client			
`

Interestingly enough, there's a similar problem with AutoDependencyProperty.Fody (http://blog.angeloflogic.com/2014/12/no-more-dependencyproperty-with.html). If you don't have a direct reference to WindowsBase type, the assembly is removed and you get compilation error. I added the WindowsBase type usage and it helped for AutoDependencyProperty.Fody but not for your plugin. Any ideas?

**Comment by ygoe** [comment]
Can you provide a sample project that does not use anything from WindowsBase? I believe everything WPF requires that so I haven't had that situation yet.

In the last-published version of ViewModelKit, References.cs line 54 tries to find the reference to the ViewModelKit helper assembly. If you just installed the NuGet package and did not make any use of ViewModelKit-provided types, this will fail. It's "fixed" in an uncommitted version in a way that it will tell you what the actual problem is (`throw new Exception("ViewModelKit assembly is not referenced from the processed assembly.");`). Please try to make use of ViewModelKit and see if that helps.
